spring:
  application:
    name: sink-notification-service
  mail:
    host: ${MAIL_SERVER_HOST}
    port: ${MAIL_SERVER_PORT}
    username: ${MAIL_SERVER_USER}
    password: ${MAIL_SERVER_PASSWORD}
solace:
  java:
    host: ${SOLACE_BROKER_SMF_URL:tcp://localhost:55554}
    msg-vpn: ${SOLACE_BROKER_VPN:default}
    clientUsername: ${SOLACE_BROKER_USERNAME:admin}
    clientPassword: ${SOLACE_BROKER_PASSWORD:secret}
    queue: ${SOLACE_QUEUE}

notification:
  mailFrom: ${NOTIFICATION_MAIL_FROM}
  mailTo: ${NOTIFICATION_MAIL_TO}
  mailSubject: ${NOTIFICATION_MAIL_SUBJECT}
  mailBodyNode: ${NOTIFICATION_MAIL_BODY_NODE}

server:
  port: 8090